[colors.primary]
background = "#110e22"
foreground = "#c3c2c7"

[colors.cursor]
text = "#110e22"
cursor = "#c3c2c7"

[colors.vi_mode_cursor]
text = "#110e22"
cursor = "#c3c2c7"

[colors.search.matches]
foreground = "#110e22"
background = "#c3c2c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#615e72"
background = "#c3c2c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#110e22"
red = "#6D71B4"
green = "#737AC2"
yellow = "#82709B"
blue = "#8F749E"
magenta = "#A07CC3"
cyan = "#9F8DAE"
white = "#c3c2c7"

[colors.bright]
black = "#615e72"
red = "#6D71B4"
green = "#737AC2"
yellow = "#82709B"
blue = "#8F749E"
magenta = "#A07CC3"
cyan = "#9F8DAE"
white = "#c3c2c7"

[colors.dim]
black = "#c3c2c7"
red = "#6D71B4"
green = "#A07CC3"
yellow = "#82709B"
blue = "#8F749E"
magenta = "#737AC2"
cyan = "#9F8DAE"
white = "#615e72"

