# Shell variables
# Generated by 'wal'
wallpaper="/home/dxrie/Documents/aesthetic-wallpapers/images/forest.png"

# Special
background='#0f1424'
foreground='#c3c4c8'
cursor='#c3c4c8'

# Colors
color0='#0f1424'
color1='#978B6E'
color2='#2E6097'
color3='#5B6AA5'
color4='#3276C2'
color5='#4E9FCE'
color6='#5AA3D7'
color7='#c3c4c8'
color8='#5e6374'
color9='#978B6E'
color10='#2E6097'
color11='#5B6AA5'
color12='#3276C2'
color13='#4E9FCE'
color14='#5AA3D7'
color15='#c3c4c8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
