[colors]
background = '#0f20248e'
black = '#0f2024'
blue = '#B26E4E'
cursor = '#c3c7c8'
cyan = '#2F8379'
foreground = '#c3c7c8'
green = '#608A7A'
magenta = '#AA9473'
red = '#FA8F44'
tabs = '#c3c7c8'
tabs-active = '#E5965F'
white = '#c3c7c8'
yellow = '#c3c7c8'
dim-black = '#0f20248e'
dim-blue = '#B26E4E8e'
dim-cyan = '#2F83798e'
dim-foreground = '#c3c7c88e'
dim-green = '#608A7A8e'
dim-magenta = '#AA94738e'
dim-red = '#FA8F448e'
dim-white = '#E5965F8e'
dim-yellow = '#c3c7c88e'
light-black = '#B26E4E'
light-blue = '#2F8379'
light-cyan = '#608A7A'
light-foreground = '#AA9473'
light-green = '#FA8F44'
light-magenta = '#E5965F'
light-red = '#c3c7c8'
light-white = '#B26E4E'
light-yellow = '#2F8379'
