[colors.primary]
background = "#141c31"
foreground = "#c4c6cb"

[colors.cursor]
text = "#141c31"
cursor = "#c4c6cb"

[colors.vi_mode_cursor]
text = "#141c31"
cursor = "#c4c6cb"

[colors.search.matches]
foreground = "#141c31"
background = "#c4c6cb"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#646a7a"
background = "#c4c6cb"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#141c31"
red = "#C6B978"
green = "#546D8B"
yellow = "#A26FBC"
blue = "#649390"
magenta = "#51AAA9"
cyan = "#B4A8BC"
white = "#c4c6cb"

[colors.bright]
black = "#646a7a"
red = "#C6B978"
green = "#546D8B"
yellow = "#A26FBC"
blue = "#649390"
magenta = "#51AAA9"
cyan = "#B4A8BC"
white = "#c4c6cb"

[colors.dim]
black = "#c4c6cb"
red = "#C6B978"
green = "#51AAA9"
yellow = "#A26FBC"
blue = "#649390"
magenta = "#546D8B"
cyan = "#B4A8BC"
white = "#646a7a"

