[colors.primary]
background = "#0f2024"
foreground = "#c3c7c8"

[colors.cursor]
text = "#0f2024"
cursor = "#c3c7c8"

[colors.vi_mode_cursor]
text = "#0f2024"
cursor = "#c3c7c8"

[colors.search.matches]
foreground = "#0f2024"
background = "#c3c7c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e7074"
background = "#c3c7c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f2024"
red = "#B26E4E"
green = "#2F8379"
yellow = "#608A7A"
blue = "#AA9473"
magenta = "#FA8F44"
cyan = "#E5965F"
white = "#c3c7c8"

[colors.bright]
black = "#5e7074"
red = "#B26E4E"
green = "#2F8379"
yellow = "#608A7A"
blue = "#AA9473"
magenta = "#FA8F44"
cyan = "#E5965F"
white = "#c3c7c8"

[colors.dim]
black = "#c3c7c8"
red = "#B26E4E"
green = "#FA8F44"
yellow = "#608A7A"
blue = "#AA9473"
magenta = "#2F8379"
cyan = "#E5965F"
white = "#5e7074"

