[colors.primary]
background = "#0f1424"
foreground = "#c3c4c8"

[colors.cursor]
text = "#0f1424"
cursor = "#c3c4c8"

[colors.vi_mode_cursor]
text = "#0f1424"
cursor = "#c3c4c8"

[colors.search.matches]
foreground = "#0f1424"
background = "#c3c4c8"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5e6374"
background = "#c3c4c8"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f1424"
red = "#978B6E"
green = "#2E6097"
yellow = "#5B6AA5"
blue = "#3276C2"
magenta = "#4E9FCE"
cyan = "#5AA3D7"
white = "#c3c4c8"

[colors.bright]
black = "#5e6374"
red = "#978B6E"
green = "#2E6097"
yellow = "#5B6AA5"
blue = "#3276C2"
magenta = "#4E9FCE"
cyan = "#5AA3D7"
white = "#c3c4c8"

[colors.dim]
black = "#c3c4c8"
red = "#978B6E"
green = "#4E9FCE"
yellow = "#5B6AA5"
blue = "#3276C2"
magenta = "#2E6097"
cyan = "#5AA3D7"
white = "#5e6374"

