[colors]
background = '#0e14208e'
black = '#0e1420'
blue = '#A25C62'
cursor = '#c2c4c7'
cyan = '#B29B74'
foreground = '#c2c4c7'
green = '#697689'
magenta = '#9C7D85'
red = '#788391'
tabs = '#c2c4c7'
tabs-active = '#9B9FA7'
white = '#c2c4c7'
yellow = '#c2c4c7'
dim-black = '#0e14208e'
dim-blue = '#A25C628e'
dim-cyan = '#B29B748e'
dim-foreground = '#c2c4c78e'
dim-green = '#6976898e'
dim-magenta = '#9C7D858e'
dim-red = '#7883918e'
dim-white = '#9B9FA78e'
dim-yellow = '#c2c4c78e'
light-black = '#A25C62'
light-blue = '#B29B74'
light-cyan = '#697689'
light-foreground = '#9C7D85'
light-green = '#788391'
light-magenta = '#9B9FA7'
light-red = '#c2c4c7'
light-white = '#A25C62'
light-yellow = '#B29B74'
