[colors.primary]
background = "#242d1e"
foreground = "#c8cac6"

[colors.cursor]
text = "#242d1e"
cursor = "#c8cac6"

[colors.vi_mode_cursor]
text = "#242d1e"
cursor = "#c8cac6"

[colors.search.matches]
foreground = "#242d1e"
background = "#c8cac6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6e7c65"
background = "#c8cac6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#242d1e"
red = "#A5C25D"
green = "#467687"
yellow = "#3CA7BF"
blue = "#57949D"
magenta = "#A7AC97"
cyan = "#B8C0AC"
white = "#c8cac6"

[colors.bright]
black = "#6e7c65"
red = "#A5C25D"
green = "#467687"
yellow = "#3CA7BF"
blue = "#57949D"
magenta = "#A7AC97"
cyan = "#B8C0AC"
white = "#c8cac6"

[colors.dim]
black = "#c8cac6"
red = "#A5C25D"
green = "#A7AC97"
yellow = "#3CA7BF"
blue = "#57949D"
magenta = "#467687"
cyan = "#B8C0AC"
white = "#6e7c65"

