[colors]
background = '#110e228e'
black = '#110e22'
blue = '#6D71B4'
cursor = '#c3c2c7'
cyan = '#737AC2'
foreground = '#c3c2c7'
green = '#82709B'
magenta = '#8F749E'
red = '#A07CC3'
tabs = '#c3c2c7'
tabs-active = '#9F8DAE'
white = '#c3c2c7'
yellow = '#c3c2c7'
dim-black = '#110e228e'
dim-blue = '#6D71B48e'
dim-cyan = '#737AC28e'
dim-foreground = '#c3c2c78e'
dim-green = '#82709B8e'
dim-magenta = '#8F749E8e'
dim-red = '#A07CC38e'
dim-white = '#9F8DAE8e'
dim-yellow = '#c3c2c78e'
light-black = '#6D71B4'
light-blue = '#737AC2'
light-cyan = '#82709B'
light-foreground = '#8F749E'
light-green = '#A07CC3'
light-magenta = '#9F8DAE'
light-red = '#c3c2c7'
light-white = '#6D71B4'
light-yellow = '#737AC2'
