[colors]
background = '#0f14248e'
black = '#0f1424'
blue = '#978B6E'
cursor = '#c3c4c8'
cyan = '#2E6097'
foreground = '#c3c4c8'
green = '#5B6AA5'
magenta = '#3276C2'
red = '#4E9FCE'
tabs = '#c3c4c8'
tabs-active = '#5AA3D7'
white = '#c3c4c8'
yellow = '#c3c4c8'
dim-black = '#0f14248e'
dim-blue = '#978B6E8e'
dim-cyan = '#2E60978e'
dim-foreground = '#c3c4c88e'
dim-green = '#5B6AA58e'
dim-magenta = '#3276C28e'
dim-red = '#4E9FCE8e'
dim-white = '#5AA3D78e'
dim-yellow = '#c3c4c88e'
light-black = '#978B6E'
light-blue = '#2E6097'
light-cyan = '#5B6AA5'
light-foreground = '#3276C2'
light-green = '#4E9FCE'
light-magenta = '#5AA3D7'
light-red = '#c3c4c8'
light-white = '#978B6E'
light-yellow = '#2E6097'
