# Shell variables
# Generated by 'wal'
wallpaper="/home/dxrie/Documents/aesthetic-wallpapers/images/a_cartoon_of_a_house_on_a_cliff.png"

# Special
background='#242d1e'
foreground='#c8cac6'
cursor='#c8cac6'

# Colors
color0='#242d1e'
color1='#A5C25D'
color2='#467687'
color3='#3CA7BF'
color4='#57949D'
color5='#A7AC97'
color6='#B8C0AC'
color7='#c8cac6'
color8='#6e7c65'
color9='#A5C25D'
color10='#467687'
color11='#3CA7BF'
color12='#57949D'
color13='#A7AC97'
color14='#B8C0AC'
color15='#c8cac6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
