# Shell variables
# Generated by 'wal'
wallpaper="/home/dxrie/Documents/aesthetic-wallpapers/images/17.png"

# Special
background='#0e1420'
foreground='#c2c4c7'
cursor='#c2c4c7'

# Colors
color0='#0e1420'
color1='#A25C62'
color2='#B29B74'
color3='#697689'
color4='#9C7D85'
color5='#788391'
color6='#9B9FA7'
color7='#c2c4c7'
color8='#5d6472'
color9='#A25C62'
color10='#B29B74'
color11='#697689'
color12='#9C7D85'
color13='#788391'
color14='#9B9FA7'
color15='#c2c4c7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
