--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dxrie/Documents/aesthetic-wallpapers/images/a_cartoon_of_a_house_on_a_cliff.png"

-- Special
background="#242d1e"
foreground="#c8cac6"
cursor="#c8cac6"

-- Colors
color0="#242d1e"
color1="#A5C25D"
color2="#467687"
color3="#3CA7BF"
color4="#57949D"
color5="#A7AC97"
color6="#B8C0AC"
color7="#c8cac6"
color8="#6e7c65"
color9="#A5C25D"
color10="#467687"
color11="#3CA7BF"
color12="#57949D"
color13="#A7AC97"
color14="#B8C0AC"
color15="#c8cac6"
