[colors.primary]
background = "#0a090c"
foreground = "#c1c1c2"

[colors.cursor]
text = "#0a090c"
cursor = "#c1c1c2"

[colors.vi_mode_cursor]
text = "#0a090c"
cursor = "#c1c1c2"

[colors.search.matches]
foreground = "#0a090c"
background = "#c1c1c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#565669"
background = "#c1c1c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0a090c"
red = "#A04F5F"
green = "#3D6F87"
yellow = "#56758C"
blue = "#AD758A"
magenta = "#6B90A8"
cyan = "#7BACC7"
white = "#c1c1c2"

[colors.bright]
black = "#565669"
red = "#A04F5F"
green = "#3D6F87"
yellow = "#56758C"
blue = "#AD758A"
magenta = "#6B90A8"
cyan = "#7BACC7"
white = "#c1c1c2"

[colors.dim]
black = "#c1c1c2"
red = "#A04F5F"
green = "#6B90A8"
yellow = "#56758C"
blue = "#AD758A"
magenta = "#3D6F87"
cyan = "#7BACC7"
white = "#565669"

