--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dxrie/Documents/aesthetic-wallpapers/images/cute-town.png"

-- Special
background="#0F0F04"
foreground="#c3c3c0"
cursor="#c3c3c0"

-- Colors
color0="#0F0F04"
color1="#635F4E"
color2="#906733"
color3="#C76A38"
color4="#90714D"
color5="#6E8A39"
color6="#A6915E"
color7="#c3c3c0"
color8="#686855"
color9="#635F4E"
color10="#906733"
color11="#C76A38"
color12="#90714D"
color13="#6E8A39"
color14="#A6915E"
color15="#c3c3c0"
