--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dxrie/Documents/aesthetic-wallpapers/images/japan3.jpg"

-- Special
background="#0a090c"
foreground="#c1c1c2"
cursor="#c1c1c2"

-- Colors
color0="#0a090c"
color1="#A04F5F"
color2="#3D6F87"
color3="#56758C"
color4="#AD758A"
color5="#6B90A8"
color6="#7BACC7"
color7="#c1c1c2"
color8="#565669"
color9="#A04F5F"
color10="#3D6F87"
color11="#56758C"
color12="#AD758A"
color13="#6B90A8"
color14="#7BACC7"
color15="#c1c1c2"
