[colors.primary]
background = "#12101e"
foreground = "#c3c3c6"

[colors.cursor]
text = "#12101e"
cursor = "#c3c3c6"

[colors.vi_mode_cursor]
text = "#12101e"
cursor = "#c3c3c6"

[colors.search.matches]
foreground = "#12101e"
background = "#c3c3c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f5d71"
background = "#c3c3c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#12101e"
red = "#8C7893"
green = "#7C819B"
yellow = "#A293A9"
blue = "#CAA7B9"
magenta = "#BAB6C4"
cyan = "#CABAC3"
white = "#c3c3c6"

[colors.bright]
black = "#5f5d71"
red = "#8C7893"
green = "#7C819B"
yellow = "#A293A9"
blue = "#CAA7B9"
magenta = "#BAB6C4"
cyan = "#CABAC3"
white = "#c3c3c6"

[colors.dim]
black = "#c3c3c6"
red = "#8C7893"
green = "#BAB6C4"
yellow = "#A293A9"
blue = "#CAA7B9"
magenta = "#7C819B"
cyan = "#CABAC3"
white = "#5f5d71"

