[colors.primary]
background = "#0e1420"
foreground = "#c2c4c7"

[colors.cursor]
text = "#0e1420"
cursor = "#c2c4c7"

[colors.vi_mode_cursor]
text = "#0e1420"
cursor = "#c2c4c7"

[colors.search.matches]
foreground = "#0e1420"
background = "#c2c4c7"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5d6472"
background = "#c2c4c7"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0e1420"
red = "#A25C62"
green = "#B29B74"
yellow = "#697689"
blue = "#9C7D85"
magenta = "#788391"
cyan = "#9B9FA7"
white = "#c2c4c7"

[colors.bright]
black = "#5d6472"
red = "#A25C62"
green = "#B29B74"
yellow = "#697689"
blue = "#9C7D85"
magenta = "#788391"
cyan = "#9B9FA7"
white = "#c2c4c7"

[colors.dim]
black = "#c2c4c7"
red = "#A25C62"
green = "#788391"
yellow = "#697689"
blue = "#9C7D85"
magenta = "#B29B74"
cyan = "#9B9FA7"
white = "#5d6472"

