[colors.primary]
background = "#0F0F04"
foreground = "#c3c3c0"

[colors.cursor]
text = "#0F0F04"
cursor = "#c3c3c0"

[colors.vi_mode_cursor]
text = "#0F0F04"
cursor = "#c3c3c0"

[colors.search.matches]
foreground = "#0F0F04"
background = "#c3c3c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#686855"
background = "#c3c3c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0F0F04"
red = "#635F4E"
green = "#906733"
yellow = "#C76A38"
blue = "#90714D"
magenta = "#6E8A39"
cyan = "#A6915E"
white = "#c3c3c0"

[colors.bright]
black = "#686855"
red = "#635F4E"
green = "#906733"
yellow = "#C76A38"
blue = "#90714D"
magenta = "#6E8A39"
cyan = "#A6915E"
white = "#c3c3c0"

[colors.dim]
black = "#c3c3c0"
red = "#635F4E"
green = "#6E8A39"
yellow = "#C76A38"
blue = "#90714D"
magenta = "#906733"
cyan = "#A6915E"
white = "#686855"

