# pywal theme for ghostty

background = 110e22
foreground = c3c2c7
cursor-color = c3c2c7
selection-background = c3c2c7
selection-foreground = 110e22

palette = 0=#110e22
palette = 1=#6D71B4
palette = 2=#737AC2
palette = 3=#82709B
palette = 4=#8F749E
palette = 5=#A07CC3
palette = 6=#9F8DAE
palette = 7=#c3c2c7
palette = 8=#615e72
palette = 9=#6D71B4
palette = 10=#737AC2
palette = 11=#82709B
palette = 12=#8F749E
palette = 13=#A07CC3
palette = 14=#9F8DAE
palette = 15=#c3c2c7
